### ISSUE TITLE
input fastq files

### ISSUE THREAD

**Issue by luoqing90** [kendrahong/TelomereCounter#1]
Hello, there!
We have two fastq files. But the program only accept one reads input file (.txt.gz).
How should I prepare the input reads file? Should I gzip the two fastq files for one sample into one .txt.gz file?

Thanks!

**Comment by kendrahong** [comment]
Hi, The data files we were working with had paired reads that were stored in one fastq file. If you have paired reads that are stored in two fastq files, you can try using bioinformatic tools described in this paper: Comparative analysis of whole genome sequencing-based telomere length measurement techniques (http://www.sciencedirect.com/science/article/pii/S1046202316302638)

Thanks!
